services:
  web_boleta:
    build: .
    container_name: contenedor_pagina_boletas
    ports: -"8082:80"
    restart: always

  services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
